### ISSUE TITLE
解决一些疑难问题

### ISSUE THREAD

**Issue by ba0gu0** [cleverbao/520apkhook#1]
1. 腾讯系列app无法找到App默认启动组件`.method public onCreate()V`，统一输入组件地址为`WorkDir/dexfile/app/classes/com/tencent/tinker/loader/app/TinkerApplication.smali`
2. 网易系列闪退暂未解决

**Comment by jmynihao** [comment]
其他系列的启动组件去哪里找呀？

**Comment by xbai8** [comment]
按照这个路径提示：输入的文件路径不存在，请重试...

**Comment by 114514xian** [comment]
> 1. 腾讯系列app无法找到App默认启动组件，统一输入组件地址为`.method public onCreate()V``WorkDir/dexfile/app/classes/com/tencent/tinker/loader/app/TinkerApplication.smali`
> 2. 网易系列闪退暂未解决

路径不存在...还有别的解决办法吗

**Comment by fexcode** [comment]
loader里面就没有app了

**Comment by fexcode** [comment]
微信是  ``WorkDir/dexfile/app/classes/com/tencent/tinker/lib/service/TinkerPatchService$InnerService.smali ``

**Comment by fexcode** [comment]
对了,注入之后还是会被有时候杀软识别出来.强制安装却无法控制

**Comment by hsbugs** [comment]
注入签名后全都闪退
