### ISSUE TITLE
注入完的APK打开空指针

### ISSUE THREAD

**Issue by bystart** [cleverbao/520apkhook#11]
对多个APK进行注入分别测试后，发现所有的app能够正常安装进入启动页面，后续就会造成空指针闪退
使用机型：小米9
系统版本：MIUI 12.5.6
JDK版本：ARM64 openjdk version "11.0.16" 2022-07-19 OpenJDK 64-Bit
Python3版本：Python 3.10.5

**Comment by bystart** [comment]
补充一张截图### 
![Uploading AA9A0F1A3231162CB00D57B23C7D59D8.jpg…]()

**Comment by bystart** [comment]
![AA9A0F1A3231162CB00D57B23C7D59D8](https://user-images.githubusercontent.com/38885210/206614417-72b07ee4-1de4-4db9-8575-90e3e7898e24.jpg)

**Comment by bystart** [comment]
系统版本：Linux node1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
python3版本：Python 3.6.8
JDK版本：java version "11.0.15.1" 2022-04-22 LTS
还是会出现闪退的问题

**Comment by Mangofang** [comment]
貌似是同样的问题，有解决吗
