### ISSUE TITLE
无法安装运行

### ISSUE THREAD

**Issue by xyjl-ly** [cleverbao/520apkhook#14]
根据提示下载配置，
 ~/Downloads/京东.apk ~/Downloads/msf.apk 最终生成的520apk
构造后发现在模拟器android 6 7 9 10 11都无法运行，麻烦问下应用啥版本呢？

**Comment by ba0gu0** [comment]
忘记了添加32为apk支持了，裂开。。。
找一个64位的apk文件（将apk解压缩，lib目录下存在arm64-v8目录）试试，QQ应该可以

下个版本换虚拟机，把32位加上。

**Comment by xyjl-ly** [comment]
现在看起来，好了一些。
将~/Downloads/QQ.apk ~/Downloads/msf.apk  绑定后可以生成，也可以安装在模拟器android  10中
打开QQ后直接闪退（第一次进入会让选做协议是否同意）。 可能还有一些小问题需要调整

**Comment by ba0gu0** [comment]
新版本添加了32位app支持，目前测试过京东（32位）、优酷（64位）都可用。在安卓5-12版本可用。

**Comment by xyjl-ly** [comment]
现在好像又不一样了
org.dom4j.DocumentException: Error on line 6 of document file:///home/qp/apk/workDir/payloadApkDecodeDir/AndroidManifest-New.xml : 已经为元素 "receiver" 指定绑定到名称空间 "http://schemas.android.com/apk/res/android" 的属性 "exported"。

**Comment by ba0gu0** [comment]
> 现在好像又不一样了 org.dom4j.DocumentException: Error on line 6 of document file:///home/qp/apk/workDir/payloadApkDecodeDir/AndroidManifest-New.xml : 已经为元素 "receiver" 指定绑定到名称空间 "http://schemas.android.com/apk/res/android" 的属性 "exported"。

下载最新的，有更新。
