### ISSUE TITLE
没法编译

### ISSUE THREAD

**Issue by CHINA-china** [cleverbao/520apkhook#15]
W: C:\Users\xxx\Downloads\workDir\apkBoxDecodeDir\res\values\strings.xml:21: error: Error parsing XML: not well-formed (invalid token)
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\xxx\AppData\Local\Temp\brut_util_Jar_9531012300126581481943319605938899655.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 28, --version-code, 39, --version-name, 1.0.0, --no-version-vectors, -F, C:\Users\xxx\AppData\Local\Temp\APKTOOL13546282770571653699.tmp, -e, C:\Users\xxx\AppData\Local\Temp\APKTOOL2333949434430769853.tmp, -0, arsc, -I, C:\Users\xxx\AppData\Local\apktool\framework\1.apk, -S, C:\Users\xxx\Downloads\workDir\apkBoxDecodeDir\res, -M, C:\Users\xxx\Downloads\workDir\apkBoxDecodeDir\AndroidManifest.xml]

**Comment by ba0gu0** [comment]
在kali中测试一下呢？应该是环境的问题。
开发所使用的java版本位java11，或者尝试使用java11以上版本运行。

**Comment by CHINA-china** [comment]
kali中也尝试过报一样得错误，使用得是java11

**Comment by ba0gu0** [comment]
能提供下被注入的apk和运行的参数吗

**Comment by CHINA-china** [comment]
被注入得apk为https://github.com/listen1/listen1_mobile/releases/tag/v0.8.2
运行参数为java -jar a520ApkHook-1.0-jar-with-dependencies.jar ./listen1_0.8.2.apk ./Ahmyth.apk
报错为：
![image](https://github.com/ba0gu0/520apkhook/assets/92798047/166343ce-f977-4b9d-b3f5-f9070a1c4e42)

**Comment by xyjl-ly** [comment]
这是资源文件文件，将提示的资源文件复制过去，从新编译（只是编译不是从头运行）

**Comment by CHINA-china** [comment]
不是很明白，有具体点得吗，复杂那个文件到哪里，如何重新编译

**Comment by ba0gu0** [comment]
> 被注入得apk为https://github.com/listen1/listen1_mobile/releases/tag/v0.8.2 运行参数为java -jar a520ApkHook-1.0-jar-with-dependencies.jar ./listen1_0.8.2.apk ./Ahmyth.apk 报错为： ![image](https://user-images.githubusercontent.com/92798047/243295176-166343ce-f977-4b9d-b3f5-f9070a1c4e42.png)

试一下非中文路径呢。

**Comment by CHINA-china** [comment]
使用了最新版仍然报错，非中文路径
![image](https://github.com/ba0gu0/520apkhook/assets/92798047/33cadb27-01aa-4ee6-891c-46048a5a8d24)

**Comment by ba0gu0** [comment]
> 使用了最新版仍然报错，非中文路径 ![image](https://user-images.githubusercontent.com/92798047/243301957-33cadb27-01aa-4ee6-891c-46048a5a8d24.png)

稍等，这个新增的功能，我改一下重新发布。

**Comment by CHINA-china** [comment]
1.0 非中文路径还是报老错误
![image](https://github.com/ba0gu0/520apkhook/assets/92798047/7af63761-6212-4654-a827-1537fcda9311)

**Comment by ba0gu0** [comment]
> 1.0 非中文路径还是报老错误 ![image](https://user-images.githubusercontent.com/92798047/243302538-7af63761-6212-4654-a827-1537fcda9311.png)

下载最新的，1.1 的试一下，不要有中文路径。

Ahmyth能正常上线吗？可以先正常生成一个，不进行app注入，上线测试一下。（我之前测试，直接生成的好像都不能上线）。

**Comment by CHINA-china** [comment]
我使用得是https://github.com/Morsmalleo/AhMyth这个项目得，最新版仍然不行，不过我知道问题所在了，复制/root/Test/workDir/payloadApkDecodeDir/res/xml/device_admin.xml到/root/Test/workDir/apkBoxDecodeDir/res/xml/，然后重新使用java -jar apktool.jar b /root/Test/workDir/apkBoxDecodeDir/  -o 1212.apk打包，就行了，不过无法安装，应该是签名的问题，似乎也无法免杀，vivo手机管家报毒

**Comment by ba0gu0** [comment]
> 我使用得是[https://github.com/Morsmalleo/AhMyth这个项目得，最新版仍然不行，不过我知道问题所在了，复制/root/Test/workDir/payloadApkDecodeDir/res/xml/device_admin.xml到/root/Test/workDir/apkBoxDecodeDir/res/xml/，然后重新使用java](https://github.com/Morsmalleo/AhMyth%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E5%BE%97%EF%BC%8C%E6%9C%80%E6%96%B0%E7%89%88%E4%BB%8D%E7%84%B6%E4%B8%8D%E8%A1%8C%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%88%91%E7%9F%A5%E9%81%93%E9%97%AE%E9%A2%98%E6%89%80%E5%9C%A8%E4%BA%86%EF%BC%8C%E5%A4%8D%E5%88%B6/root/Test/workDir/payloadApkDecodeDir/res/xml/device_admin.xml%E5%88%B0/root/Test/workDir/apkBoxDecodeDir/res/xml/%EF%BC%8C%E7%84%B6%E5%90%8E%E9%87%8D%E6%96%B0%E4%BD%BF%E7%94%A8java) -jar apktool.jar b /root/Test/workDir/apkBoxDecodeDir/ -o 1212.apk打包，就行了，不过无法安装，应该是签名的问题，似乎也无法免杀，vivo手机管家报毒

已找到原因，因为要把远控的AndroidManifest .xml文件合并到新生成的app中，会牵扯到不同的远控软件，引用的一些资源没复制过来。研究下怎么统一解决这类资源问题。之前测试都是在msf和AhMyth的原版项目里面测的，里面没多余的资源引用。

关于免杀的问题，是不是安全警告呀，不应该是报毒，对于手机管家来说，只要签名不是白名单里面的，自己开发的app，没毒也会警告的。
真正报毒的页面，你可以安装个msf的apk看一下，应该不一样的。

**Comment by CHINA-china** [comment]
晚上又试试了，手动使用apktool打包、签名，不报毒了，但是无法正常运行，闪退

**Comment by ba0gu0** [comment]
> 晚上又试试了，手动使用apktool打包、签名，不报毒了，但是无法正常运行，闪退

下载最新版本的，应该没问题了。但是上线不了。
可以试试msf的apk。可以正常使用。

我先调试一下AhMyth

**Comment by CHINA-china** [comment]
1.0可以正常使用，但是报毒
![image](https://github.com/ba0gu0/520apkhook/assets/92798047/5f6e8d5f-bd3d-473f-9332-8c08342df7e9)
![5D7E8918A88ECC3DCFA5775D39884623](https://github.com/ba0gu0/520apkhook/assets/92798047/9dd3046e-b1b2-44f8-8c3d-52aa6ec5bbde)

1.1无法使用，原因是被注入的apk，解包后不存在/workDir/payloadApkDecodeDir/res/xml路径中的xml文件夹
![image](https://github.com/ba0gu0/520apkhook/assets/92798047/7aa5427b-b1de-40a7-892f-e7447d20e987)

**Comment by ba0gu0** [comment]
> 1.0可以正常使用，但是报毒 ![image](https://user-images.githubusercontent.com/92798047/243356221-5f6e8d5f-bd3d-473f-9332-8c08342df7e9.png) ![5D7E8918A88ECC3DCFA5775D39884623](https://user-images.githubusercontent.com/92798047/243356656-9dd3046e-b1b2-44f8-8c3d-52aa6ec5bbde.jpg)
> 
> 1.1无法使用，原因是被注入的apk，解包后不存在/workDir/payloadApkDecodeDir/res/xml路径中的xml文件夹 ![image](https://user-images.githubusercontent.com/92798047/243356485-7aa5427b-b1de-40a7-892f-e7447d20e987.png)

下载最新版的，

[https://github.com/ba0gu0/520apkhook/releases/download/v1.1/a520ApkHook-1.1-jar-with-dependencies.jar](https://github.com/ba0gu0/520apkhook/releases/download/v1.1/a520ApkHook-1.1-jar-with-dependencies.jar)

始终这个命令生成，这个是针对你之前发的Ahmyth版本使用的。

```
java -jar a520ApkHook-1.1-jar-with-dependencies.jar  -o -s ahmyth.mine.king.ahmyth.MainService youku.apk Ahmyth-aligned-debugSigned.apk

```

报毒的问题，有空找几个手机试试吧。
