### ISSUE TITLE
基于master分支，编译不通过，缺少top.niunaijun.blackbox.core.env 下的java文件

### ISSUE THREAD

**Issue by Selinallg** [cleverbao/520apkhook#18]
![image](https://github.com/ba0gu0/520apkhook/assets/18552304/7771d8bf-3684-4360-b13f-12b41ee33577)

**Comment by ba0gu0** [comment]
> ![image](https://user-images.githubusercontent.com/18552304/243934014-7771d8bf-3684-4360-b13f-12b41ee33577.png)


.gitignore的问题，env目录没有push上来。

<img width="407" alt="image" src="https://github.com/ba0gu0/520apkhook/assets/19379443/f02ac4ea-90b9-4977-8e5f-d8ef8307d3b8">

更新了，重新拉一下。
