### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by mortal-sec** [cleverbao/520apkhook#19]
![image](https://github.com/ba0gu0/520apkhook/assets/95933876/30d3ec3e-3be9-4166-b641-d895dbb2e5c7)
![image](https://github.com/ba0gu0/520apkhook/assets/95933876/f5112212-3ddf-4390-9731-5f4f464aba43)

**Comment by ba0gu0** [comment]
> ![image](https://user-images.githubusercontent.com/95933876/244079205-30d3ec3e-3be9-4166-b641-d895dbb2e5c7.png) ![image](https://user-images.githubusercontent.com/95933876/244079460-f5112212-3ddf-4390-9731-5f4f464aba43.png)

本来想适配安卓版本高清图标的，发现国内app没有一个按照标准来做的，这段代码已注释，下载最新版本的吧。
