### ISSUE TITLE
部分命令无法使用

### ISSUE THREAD

**Issue by little-2pig** [cleverbao/520apkhook#2]
只有部分命令有效，像geolocate 、send_sms、webcam等都不行，就看看sysinfo这些，是哪里出什么问题了呢，Android 9，msf6.1.5

**Comment by ba0gu0** [comment]
msf的问题，msfvenom正常生成的apk也没法用，msf貌似只能兼容低版本安卓。后续考虑msf换成
https://github.com/qH0sT/AndroSpy

**Comment by little-2pig** [comment]
排查了一下问题，注入的apk安装权限没给全，除了调用摄像头应用会强制退出，其他下载通讯录和电话、短信都可以，发送短信也行，可以拿来做安全意识培训展示用，。
那个师傅能借你项目写篇社区文稿嘛，会标注出处的，我也只是拿来做培训展示用

**Comment by ba0gu0** [comment]
可以展示，可以把相关权限给出吗？我更新一下脚本。

**Comment by little-2pig** [comment]
不不不，不是注入的权限没给全，是我自己安装apk权限没给全而已。。。。。。师傅的项目还是顶的

**Comment by BlackdogL** [comment]
相机权限给了 调用摄像头还是出问题 有解决办法吗
