### ISSUE TITLE
error: Error parsing XML: not well-formed

### ISSUE THREAD

**Issue by 2522595153** [cleverbao/520apkhook#20]

**Comment by ba0gu0** [comment]
请提供详细的报错信息，被注入的apk，注入的apk，java版本，操作系统环境。

**Comment by 2522595153** [comment]
java version "11.0.19" 2023-04-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.19+9-LTS-224, mixed mode)

**Comment by 2522595153** [comment]
抖音极速版  + msf.apk

**Comment by 2522595153** [comment]
![Snipaste_2023-06-08_15-33-35](https://github.com/ba0gu0/520apkhook/assets/56664312/8ec6b345-de6b-4552-ab54-6fe96aaed404)

**Comment by ba0gu0** [comment]
用kali尝试一下，顺便提供下这个xml文件，我看下咋回事。

<img width="711" alt="image" src="https://github.com/ba0gu0/520apkhook/assets/19379443/b864bad4-9e09-4f15-a168-e5fac9cf9cdd">

**Comment by ba0gu0** [comment]
<img width="790" alt="image" src="https://github.com/ba0gu0/520apkhook/assets/19379443/a3916f9a-6b8b-4496-85c3-db0dd67ce004">


不要再用Windows了，裂开。。。

**Comment by 2522595153** [comment]
linux完美解决 emmm

**Comment by 2522595153** [comment]
么么
