### ISSUE TITLE
注入后的Apk被手机管家检测出病毒

### ISSUE THREAD

**Issue by hyz1433376288** [cleverbao/520apkhook#22]
使用安卓模拟器时（雷电模拟器，安卓9），可以正常安装注入的Apk，也可以实现远控。但是在物理机上安装的时候，被检测出风险。
物理机（Redmi 3，Android 5.1.1），注入的应用为天气预报+msf.apk。
![image](https://github.com/ba0gu0/520apkhook/assets/64128854/bef4fa4f-609e-4875-8e77-fb93d4dd2a17)
![image](https://github.com/ba0gu0/520apkhook/assets/64128854/5f10c5cd-c897-4659-9391-a25a70483637)
无视风险，继续安装，开启App时，远控程序也不会上线（物理机与Kali在同一局域网下，家庭Wifi）
![image](https://github.com/ba0gu0/520apkhook/assets/64128854/23caa7ce-18ca-41c7-b498-49c3f89f964d)
![image](https://github.com/ba0gu0/520apkhook/assets/64128854/dbe33e15-f428-40d8-a257-9ab40d5db0ce)

**Comment by ba0gu0** [comment]
可以测试一下直接用msf生成的apk能否上线

**Comment by 0xtlu** [comment]
物理机（Mi 5，Android 8.0.0），注入的应用为：一言.apk+msf.apk 能上线，生成的apk闪退，无法截图、获取通信录；via.apk+msf.apk 能上线，可正常打开，但无法截图、获取通讯录。
![image](https://github.com/ba0gu0/520apkhook/assets/79645308/ca8dd4f5-3951-455c-bc69-71df62c54385)
![image](https://github.com/ba0gu0/520apkhook/assets/79645308/2d11ccea-5ab6-49f7-be1d-1334339b22c6)

**Comment by hyz1433376288** [comment]
模拟器和物理机安装msf.apk都无法运行哎，点击图标没反应

**Comment by hyz1433376288** [comment]
模拟器和物理机安装msf.apk都无法运行哎，点击图标没反应，远控也没有上线
![image](https://github.com/ba0gu0/520apkhook/assets/64128854/4f0d52d1-2421-4413-891e-73be6943e3ad)

**Comment by 953532062** [comment]
![N0RA4LNPT%BJGBCPXZN3}3M](https://github.com/ba0gu0/520apkhook/assets/64680981/0dcd6338-de1e-4f32-a2fb-4adf2209987a)
大佬，这什么情况

**Comment by ba0gu0** [comment]
后续版本会尝试混淆，绕过手机管家。
目前无法上线的问题，先测试原生的app是否能上线。app无法运行属于正常情况，目前无法对所有的app进行注入。
