### ISSUE TITLE
运行报错问题

### ISSUE THREAD

**Issue by 953532062** [cleverbao/520apkhook#23]
![image](https://github.com/ba0gu0/520apkhook/assets/64680981/092ead5b-38b9-4ba1-8c1e-f462a3b1a5ab)
大佬，这个要怎么ji解决

**Comment by ba0gu0** [comment]
换环境，找个Linux，安装java11以上版本。

**Comment by 953532062** [comment]
![image](https://github.com/ba0gu0/520apkhook/assets/64680981/eca155ba-ad60-483a-94a9-d3a8fa3a6014)
带佬，17.0版本也没有解决这个问题。
