### ISSUE TITLE
32位闪退，64位无法上线

### ISSUE THREAD

**Issue by Mangofang** [cleverbao/520apkhook#24]
![image](https://github.com/ba0gu0/520apkhook/assets/38810849/b8d05a0b-e518-40b2-a0ec-288113a642ff)
``--------- beginning of crash
--------- beginning of main
07-17 19:42:34.178 W/System.err( 8289): java.lang.ClassNotFoundException: com.metasploit.stage.MainActivity
07-17 19:42:34.178 W/System.err( 8289): 	at java.lang.Class.classForName(Native Method)
07-17 19:42:34.178 W/System.err( 8289): 	at java.lang.Class.forName(Class.java:324)
07-17 19:42:34.178 W/System.err( 8289): 	at java.lang.Class.forName(Class.java:285)
07-17 19:42:34.178 W/System.err( 8289): 	at com.v2ray.ang.a520apkbox.MainApplication.bindRealApplication(MainApplication.java:229)
07-17 19:42:34.178 W/System.err( 8289): 	at com.v2ray.ang.a520apkbox.MainApplication.onCreate(MainApplication.java:188)
07-17 19:42:34.178 W/System.err( 8289): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
07-17 19:42:34.178 W/System.err( 8289): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4894)
07-17 19:42:34.178 W/System.err( 8289): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-17 19:42:34.178 W/System.err( 8289): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
07-17 19:42:34.178 W/System.err( 8289): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-17 19:42:34.178 W/System.err( 8289): 	at android.os.Looper.loop(Looper.java:148)
07-17 19:42:34.178 W/System.err( 8289): 	at android.app.ActivityThread.main(ActivityThread.java:5654)
07-17 19:42:34.178 W/System.err( 8289): 	at java.lang.reflect.Method.invoke(Native Method)
07-17 19:42:34.178 W/System.err( 8289): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
07-17 19:42:34.178 W/System.err( 8289): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:672)
07-17 19:42:34.178 W/System.err( 8289): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.metasploit.stage.MainActivity" on path: DexPathList[[zip file "/data/app/com.v2ray.ang.a520apkbox-1/base.apk"],nativeLibraryDirectories=[/data/app/com.v2ray.ang.a520apkbox-1/lib/arm64, /data/app/com.v2ray.ang.a520apkbox-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
07-17 19:42:34.178 W/System.err( 8289): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-17 19:42:34.178 W/System.err( 8289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-17 19:42:34.178 W/System.err( 8289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-17 19:42:34.178 W/System.err( 8289): 	... 15 more
07-17 19:42:34.178 W/System.err( 8289): 	Suppressed: java.lang.ClassNotFoundException: com.metasploit.stage.MainActivity
07-17 19:42:34.179 W/System.err( 8289): 		at java.lang.Class.classForName(Native Method)
07-17 19:42:34.179 W/System.err( 8289): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-17 19:42:34.179 W/System.err( 8289): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-17 19:42:34.179 W/System.err( 8289): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-17 19:42:34.179 W/System.err( 8289): 		... 16 more
07-17 19:42:34.179 W/System.err( 8289): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-17 19:42:34.780 W/System.err( 8315): java.lang.ClassNotFoundException: android.hardware.location.IContextHubService$Stub
07-17 19:42:34.780 W/System.err( 8315): 	at java.lang.Class.classForName(Native Method)
07-17 19:42:34.780 W/System.err( 8315): 	at java.lang.Class.forName(Class.java:324)
07-17 19:42:34.780 W/System.err( 8315): 	at java.lang.Class.forName(Class.java:285)
07-17 19:42:34.780 W/System.err( 8315): 	at top.niunaijun.blackreflection.BlackReflection.getClassNameByBlackClass(BlackReflection.java:239)
07-17 19:42:34.780 W/System.err( 8315): 	at top.niunaijun.blackreflection.BlackReflection.create(BlackReflection.java:55)
07-17 19:42:34.780 W/System.err( 8315): 	at black.android.hardware.location.BRIContextHubServiceStub.get(BRIContextHubServiceStub.java:13)
07-17 19:42:34.780 W/System.err( 8315): 	at top.niunaijun.blackbox.fake.service.IContextHubServiceProxy.getWho(IContextHubServiceProxy.java:25)
07-17 19:42:34.780 W/System.err( 8315): 	at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.injectHook(ClassInvocationStub.java:51)
07-17 19:42:34.780 W/System.err( 8315): 	at top.niunaijun.blackbox.fake.hook.HookManager.injectAll(HookManager.java:186)
07-17 19:42:34.780 W/System.err( 8315): 	at top.niunaijun.blackbox.fake.hook.HookManager.init(HookManager.java:157)
07-17 19:42:34.780 W/System.err( 8315): 	at top.niunaijun.blackbox.BlackBoxCore.doAttachBaseContext(BlackBoxCore.java:159)
07-17 19:42:34.780 W/System.err( 8315): 	at com.v2ray.ang.a520apkbox.MainApplication.attachBaseContext(MainApplication.java:108)
07-17 19:42:34.780 W/System.err( 8315): 	at android.app.Application.attach(Application.java:257)
07-17 19:42:34.780 W/System.err( 8315): 	at android.app.Instrumentation.newApplication(Instrumentation.java:997)
07-17 19:42:34.780 W/System.err( 8315): 	at android.app.Instrumentation.newApplication(Instrumentation.java:981)
07-17 19:42:34.780 W/System.err( 8315): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:583)
07-17 19:42:34.780 W/System.err( 8315): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4867)
07-17 19:42:34.780 W/System.err( 8315): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-17 19:42:34.780 W/System.err( 8315): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
07-17 19:42:34.780 W/System.err( 8315): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-17 19:42:34.780 W/System.err( 8315): 	at android.os.Looper.loop(Looper.java:148)
07-17 19:42:34.780 W/System.err( 8315): 	at android.app.ActivityThread.main(ActivityThread.java:5654)
07-17 19:42:34.780 W/System.err( 8315): 	at java.lang.reflect.Method.invoke(Native Method)
07-17 19:42:34.780 W/System.err( 8315): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
07-17 19:42:34.780 W/System.err( 8315): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:672)
07-17 19:42:34.780 W/System.err( 8315): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.hardware.location.IContextHubService$Stub" on path: DexPathList[[zip file "/data/app/com.v2ray.ang.a520apkbox-1/base.apk"],nativeLibraryDirectories=[/data/app/com.v2ray.ang.a520apkbox-1/lib/arm64, /data/app/com.v2ray.ang.a520apkbox-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
07-17 19:42:34.780 W/System.err( 8315): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-17 19:42:34.780 W/System.err( 8315): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-17 19:42:34.780 W/System.err( 8315): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-17 19:42:34.780 W/System.err( 8315): 	... 25 more
07-17 19:42:34.780 W/System.err( 8315): 	Suppressed: java.lang.ClassNotFoundException: android.hardware.location.IContextHubService$Stub
07-17 19:42:34.780 W/System.err( 8315): 		at java.lang.Class.classForName(Native Method)
07-17 19:42:34.780 W/System.err( 8315): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-17 19:42:34.780 W/System.err( 8315): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-17 19:42:34.780 W/System.err( 8315): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-17 19:42:34.780 W/System.err( 8315): 		... 26 more
07-17 19:42:34.780 W/System.err( 8315): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-17 19:42:34.843 W/System.err( 8315): java.lang.ClassNotFoundException: com.metasploit.stage.MainActivity
07-17 19:42:34.843 W/System.err( 8315): 	at java.lang.Class.classForName(Native Method)
07-17 19:42:34.843 W/System.err( 8315): 	at java.lang.Class.forName(Class.java:324)
07-17 19:42:34.843 W/System.err( 8315): 	at java.lang.Class.forName(Class.java:285)
07-17 19:42:34.843 W/System.err( 8315): 	at com.v2ray.ang.a520apkbox.MainApplication.bindRealApplication(MainApplication.java:229)
07-17 19:42:34.843 W/System.err( 8315): 	at com.v2ray.ang.a520apkbox.MainApplication.onCreate(MainApplication.java:188)
07-17 19:42:34.843 W/System.err( 8315): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
07-17 19:42:34.843 W/System.err( 8315): 	at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callApplicationOnCreate(BaseInstrumentationDelegate.java:225)
07-17 19:42:34.843 W/System.err( 8315): 	at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:140)
07-17 19:42:34.843 W/System.err( 8315): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4894)
07-17 19:42:34.843 W/System.err( 8315): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-17 19:42:34.843 W/System.err( 8315): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
07-17 19:42:34.843 W/System.err( 8315): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-17 19:42:34.843 W/System.err( 8315): 	at android.os.Looper.loop(Looper.java:148)
07-17 19:42:34.843 W/System.err( 8315): 	at android.app.ActivityThread.main(ActivityThread.java:5654)
07-17 19:42:34.843 W/System.err( 8315): 	at java.lang.reflect.Method.invoke(Native Method)
07-17 19:42:34.843 W/System.err( 8315): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
07-17 19:42:34.843 W/System.err( 8315): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:672)
07-17 19:42:34.843 W/System.err( 8315): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.metasploit.stage.MainActivity" on path: DexPathList[[zip file "/data/app/com.v2ray.ang.a520apkbox-1/base.apk"],nativeLibraryDirectories=[/data/app/com.v2ray.ang.a520apkbox-1/lib/arm64, /data/app/com.v2ray.ang.a520apkbox-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
07-17 19:42:34.843 W/System.err( 8315): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-17 19:42:34.843 W/System.err( 8315): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-17 19:42:34.843 W/System.err( 8315): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-17 19:42:34.843 W/System.err( 8315): 	... 17 more
07-17 19:42:34.843 W/System.err( 8315): 	Suppressed: java.lang.ClassNotFoundException: com.metasploit.stage.MainActivity
07-17 19:42:34.843 W/System.err( 8315): 		at java.lang.Class.classForName(Native Method)
07-17 19:42:34.843 W/System.err( 8315): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-17 19:42:34.843 W/System.err( 8315): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-17 19:42:34.843 W/System.err( 8315): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-17 19:42:34.843 W/System.err( 8315): 		... 18 more
07-17 19:42:34.843 W/System.err( 8315): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by ba0gu0** [comment]
v2ray这种肯定不行，它要给系统添加vpn，无法嵌套虚拟机运行的。
注入app是把正常的app放到虚拟机里面运行，会导致部分app无法使用。
暂时没有办法解决。
