### ISSUE TITLE
重新编译模板app报错，是什么原因造成的呢？

### ISSUE THREAD

**Issue by xxwweb** [cleverbao/520apkhook#25]
![图片](https://github.com/ba0gu0/520apkhook/assets/59022436/c817852a-3487-4f03-98d6-e0fb24d1c3cf)
![图片](https://github.com/ba0gu0/520apkhook/assets/59022436/470d61ee-8f8f-429c-b1a0-c10beb8da5b3)

**Comment by ba0gu0** [comment]
可否提供一下远控app，目前测试过，msf和AhMyth-Android-RAT。
不同的远控app可能需要修改对应的资源文件。
