### ISSUE TITLE
文件有问题，教程不详细

### ISSUE THREAD

**Issue by Zz3245** [cleverbao/520apkhook#26]
文件路径错误：确保文件路径是正确的，并且文件确实存在。
文件权限问题：确保当前用户对文件具有足够的读取权限。
文件格式问题：确保文件是有效的 Apk 文件，没有被修改或损坏。
7/24 19:43:33.306 E/Main: 读取被注入Apk文件信息失败, 无法进行下一步, 程序退出! /root/Downloads/京东.apk
java.nio.file.NoSuchFileException: /root/Downloads/京东.apk

**Comment by ba0gu0** [comment]
尽量不要有中文，还有权限问题。
这种问题是基础知识，没必要在教程中说明。
