### ISSUE TITLE
生成失败

### ISSUE THREAD

**Issue by Y0n3er** [cleverbao/520apkhook#31]
![image](https://github.com/ba0gu0/520apkhook/assets/104112681/a82fe296-f1f1-4c37-a6ba-1311fd6955ca)
这是为什么

**Comment by ba0gu0** [comment]
估计是中文目录问题

**Comment by ahhhahhh** [comment]
![1702625143138](https://github.com/ba0gu0/520apkhook/assets/102953004/0006c623-00d1-44b1-8cf2-bca7b97c37d5)
我这个没有中文目录也不行

**Comment by tiantnag** [comment]
老哥你解决了吗，我也是爆这个问题

**Comment by ba0gu0** [comment]
好长时间没看了，用下面这个解决

#39
