### ISSUE TITLE
W: ERROR: resource directory '/home/kali/����/apk/workDir/apkBoxDecodeDir/res' does not exist brut.androlib.AndrolibException: brut.common.BrutException: could not exec

### ISSUE THREAD

**Issue by HSEC-RT** [cleverbao/520apkhook#32]
![image](https://github.com/ba0gu0/520apkhook/assets/94616067/6c4b150a-2791-4141-92a0-69734f0b0ce2)
这是咋回事，找了很多，有说是apktool的版本问题导致的，希望能回答，非常感谢

**Comment by ba0gu0** [comment]
找个干净的ubuntu虚拟机，安装java环境，再使用工具。不要有中文路径

**Comment by HSEC-RT** [comment]
> 找个干净的ubuntu虚拟机，安装java环境，再使用工具。不要有中文路径

你好，这个问题我解决了，目前发现有个问题就是捆绑的正常的APK的名字必须是京东.apk（就是本身APK可以是其他APK，但是名字必须是京东），然后执行那个jar包合并才能正常执行然后生成出来捆绑msf木马的APK，安装到虚拟机中的时候是可以正常安装和上线的，但是在真实手机，安卓13版本以下，安装会显示安装包损坏，请问这一问题您是否有遇到过？本地测试，不会做违法事情，请放心，麻烦有空解答一下，感谢万分
![image](https://github.com/ba0gu0/520apkhook/assets/94616067/52e4d1a6-ff9d-460b-9014-69ecb170c3dd)

**Comment by ghost** [comment]
> > 找个干净的ubuntu虚拟机，安装java环境，再使用工具。不要有中文路径
> 
> 你好，这个问题我解决了，目前发现有个问题就是捆绑的正常的APK的名字必须是京东.apk（就是本身APK可以是其他APK，但是名字必须是京东），然后执行那个jar包合并才能正常执行然后生成出来捆绑msf木马的APK，安装到虚拟机中的时候是可以正常安装和上线的，但是在真实手机，安卓13版本以下，安装会显示安装包损坏，请问这一问题您是否有遇到过？本地测试，不会做违法事情，请放心，麻烦有空解答一下，感谢万分 ![image](https://private-user-images.githubusercontent.com/94616067/293463284-52e4d1a6-ff9d-460b-9014-69ecb170c3dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTMzOTIsIm5iZiI6MTcwNzM5MzA5MiwicGF0aCI6Ii85NDYxNjA2Ny8yOTM0NjMyODQtNTJlNGQxYTYtZmY5ZC00NjBiLTkwMTQtNjllY2IxNzBjM2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDExNTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOTZjYjQ0N2IwZDcwNzA2OTEwMmM5ZDg3ZTgwMzY5NDU2YTY3YWM1NGNjNDFhZjdmNGU0YzMxZDYyOTNlZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qTROrqfc2gFCwwGwf92unvTp28NpR0G7EFQF1TrNW4w)

能告诉我一下用openjdk几的版本能用吗？实体机Kali成功，Proot容器却始终报错132！谢谢了。你那个安装不上的解决方法有两个 ，方法一，（通用方法，推荐）在
https://github.com/ba0gu0/520apkhook/issues/33 实测可以。必须用3.0.62版本，3.0.62以上版本都会失败，不能更新。如果没有安卓5-7手机用安卓8以上的手机（需要自带联网管理功能的系统）也行，就不用lbe安全大师了，只要禁止NP管理器联网即可。方法二：（懒人方法），直接纯V2签名，不过兼容性很差，基本安卓7以下别想安装了，安装报错同上图。方法三：（仅适用于高级用户），解锁BL刷面具，然后安装LSPosed加核心破解模块即可。缺点，不太安全（LSPosed已停止维护），有时容易被某些游戏的反作弊检测到（如果你有手机专门用来调试APP的，请忽略），国家反诈中心和部分网上银行App可能打不开（可以隐藏Root后打开，不过very very difficult）
