### ISSUE TITLE
不兼容

### ISSUE THREAD

**Issue by HSEC-RT** [cleverbao/520apkhook#33]
你好，目前发现有个问题就是捆绑的正常的APK的名字必须是京东.apk（就是本身APK可以是其他APK，但是名字必须是京东），然后执行那个jar包合并才能正常执行然后生成出来捆绑msf木马的APK，安装到虚拟机中的时候是可以正常安装和上线的，但是在真实手机，安卓13版本以下，安装会显示安装包损坏，请问这一问题您是否有遇到过？
![image](https://github.com/ba0gu0/520apkhook/assets/94616067/c7c21d5c-1f6a-45a2-bb0e-5a1ebdb49d91)

**Comment by ghost** [comment]
我也遇到过，原因是安卓11及以上系统不认TargetSDK≥30的APK的V1签名。
解决方法：
1.准备一个安卓7或安卓5虚拟机并Root（安卓8.0以下的已Root真机也行），LBE安全大师安装包（版本不限），NP管理器3.0.62安装包。（注意！！不能用NP管理器3.0.62以上版本）
2.虚拟机里安装NP管理器，LBE安全大师
3.打开LBE安全大师，授权Root，开启主动防御，然后禁止NP管理器的联网（这一步非常重要！不然NP管理器会闪退！）
4.复制你生成的APK到虚拟机/sdcard目录下
5.打开NP管理器，选择Apk文件，点击功能，通用编辑，把TargetSDK改成28，保存（不是必须28，推荐28是因为兼容好些，也可以更低，最低填23）
6.重新签名Apk。
收工。此时Apk就正常了，任意安卓手机可安装（理论上是，实际上有些手机需要断网安装，安装完就ok)
