### ISSUE TITLE
关于资源文件的问题

### ISSUE THREAD

**Issue by jl785917397** [cleverbao/520apkhook#35]
感谢上个问题的回复，发现了新的问题。
我的被附加的APK的资源文件strings.xml中有下边节点。然后合并APK后，这两个节点没有在合成后的APK中出现
    <string name="IP">https://127.0.0.1</string>
    <string name="port">1101</string>

**Comment by jl785917397** [comment]
//<resources>
//    <string name="app_name">NewRAT3</string>
//    <string name="IP">https://127.0.0.1</string>
//    <string name="port">1101</string>
//</resources>

**Comment by ba0gu0** [comment]
工具中有两个要素，原始app、远控app。

工具不会合并strings.xml中的内容，因为不会影响原始app的运行。

被注入的app是运行在虚拟环境中的，原始app不会被修改。

除非远控的app需要用到string.xml中的内容。不过这个很难同步过去，会有很多冲突项。

AndroidManifest.xml中的内容，已经从远控app中迁移过来了，推荐把关键内容放到这里。
