### ISSUE TITLE
你好 帮我看下这个问题怎么解决，谢谢

### ISSUE THREAD

**Issue by zhangyu668899** [cleverbao/520apkhook#36]
你好 帮我看下这个问题怎么解决，谢谢
![1235](https://github.com/ba0gu0/520apkhook/assets/155526729/1ad43c72-8b8b-4c2d-828f-239b47021826)

![photo_2024-01-07_00-47-48](https://github.com/ba0gu0/520apkhook/assets/155526729/a97b00c4-94e7-4d29-b8cd-37cf8104926e)

**Comment by ba0gu0** [comment]
* 这个一般是远控的问题，推荐换个远控。AhMyth挺不错的。

> [AhMyth](https://github.com/Morsmalleo/AhMyth/releases)
