### ISSUE TITLE
华为报毒

### ISSUE THREAD

**Issue by jl785917397** [cleverbao/520apkhook#37]
想问下华为手机报毒该怎么解决，我只能确定到是其中的Module引起的

**Comment by ba0gu0** [comment]
注入msf的apk时，没有进行混淆，在app的dex文件和xml文件中存在msf的特征，考虑下个版本加入混淆，可以参考之前的代码，把msf进行混淆，然后再用软件进行注入。

之前版本中对msf生成的apk混淆的代码。

[https://github.com/ba0gu0/520apkhook/blob/c5f0107e383e994c4ead5a6f65dd962d489c256c/utils/InjectMsf2App.py#L65-L87](https://github.com/ba0gu0/520apkhook/blob/c5f0107e383e994c4ead5a6f65dd962d489c256c/utils/InjectMsf2App.py#L65-L87)

**Comment by jl785917397** [comment]
抱歉，可能是我的描述不太准确。
我没有使用生成的msf，而是捆绑的自己写的一个简单的DEMO，这个DEMO单独安装不会报毒。
但是与目标APK合并后的APK报毒。另外单独打包APKbox然后安装，也会报毒，因此猜测报毒可能是因为APKbox造成的。
尝试过：修改APKbox的包名和对APKbox进行混淆。但是仍然报毒（只要安装上APKbox），并且合并后的APK依旧报毒。

**Comment by ba0gu0** [comment]
我日，不会是项目被华为检测了吧，进病毒库了😭

**Comment by jl785917397** [comment]
我觉得十有八九，定位到是Bcore这个库引起的，修改包名+混淆无效，怀疑是检测到了其中的字符串，但是这个库字符串太多了，我还在排查。不知道这样判断对不对，大佬你是否有更好建议。我的昵称中数字是企鹅号，可以加个好友请教下么

**Comment by Cser1** [comment]
飞行模式完事

**Comment by ba0gu0** [comment]
* 最近没事看了下，工具自带的apk的签名证书被标记了，要自己换证书。

* 推荐下面这个项目，自己重新生成一套证书，重新签名应该就可以了。
> [https://github.com/jixiaoyong/ApkSigner](https://github.com/jixiaoyong/ApkSigner)
