### ISSUE TITLE
与ahmyth生成报错 无法解决

### ISSUE THREAD

**Issue by h4x0r2024** [cleverbao/520apkhook#39]
04/24 22:36:10.593 I/HackApk: 开始复制资源文件到模板App中.
04/24 22:36:10.601 I/HackApk: 已将Payload Apk 的Dex压缩包复制到模板App的assets目录中.
04/24 22:36:10.629 I/HackApk: 已将被注入Apk复制到模板App的assets目录中.
04/24 22:36:10.630 I/HackApk: 已清空模板App中的 mipmap-xxxhdpi 文件夹.
04/24 22:36:10.632 I/HackApk: 重新向模板App中的 mipmap-xxxhdpi 文件夹复制图标文件.
04/24 22:36:10.634 I/HackApk: 已复制Payload apk中的res/xml目录到520ApkBox中.
04/24 22:36:10.635 I/HackApk: 所有资源文件已复制完成.
04/24 22:36:10.635 I/HackApk: 正在进行重新编译模板App.
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\Administrator\Downloads\workDir\apkBoxDecodeDir\res\values\strings.xml:21: error: Error parsing XML: not well-formed (invalid token)
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_126096542864238835645729860449740751592.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 34, --version-code, 248, --version-name, 2.4.8, --no-version-vectors, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL7628463462367675163.tmp, -e, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL17954077107222661684.tmp, -0, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Administrator\Downloads\workDir\apkBoxDecodeDir\res, -M, C:\Users\Administrator\Downloads\workDir\apkBoxDecodeDir\AndroidManifest.xml]

主机信息：
Windows10 22h2
java version "11.0.21" 2023-10-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.21+9-LTS-193)

远控：Ahmyth v1.0 beta5a无bind原生payload
绑定APP：京东.apk

如果需要的话，我可以提供其他主机环境信息

**Comment by ba0gu0** [comment]
## 原因

* 大概找到原因了，获取到的app的名字是`京东`，然后以gbk编码的方式保存到`workDir\apkBoxDecodeDir\res\values\strings.xml`中，然后apktool再build的时候，会出错。

* 基本上其他的中文名字的app，可能都会出现这个问题，找时间修复一下。

<img width="1511" alt="image" src="https://github.com/ba0gu0/520apkhook/assets/19379443/6b838a0a-555b-4dc1-b80e-f3d72a110fd1">


## 解决方法

* 目前的一个方法是，进入`workDir\apkBoxDecodeDir`目录，找到`res\values\strings.xml`这个文件

* 用vscode打开，文件编码先使用gbk打开，然后再使用utf8保存。

<img width="1086" alt="image" src="https://github.com/ba0gu0/520apkhook/assets/19379443/a5a59fde-e16b-4d2b-9414-d54a041a8918">

<img width="637" alt="image" src="https://github.com/ba0gu0/520apkhook/assets/19379443/6d61386c-bf0c-4d46-8666-47b65457a608">

* 注意，使用gbk打开，一定确保打开后显示正常，如果还错误，换一下编码。

<img width="1062" alt="image" src="https://github.com/ba0gu0/520apkhook/assets/19379443/4be4aa0c-2f98-4998-b58e-537716dc7491">

<img width="713" alt="image" src="https://github.com/ba0gu0/520apkhook/assets/19379443/4002a7e6-7be8-4015-8aa3-6822e4ded8f0">

* 修改完后，记得保存。

* 再进到workDir\apkBoxDecodeDir目录，执行命令 `java -jar ..\libs\apktool.jar b -o ..\..\520ApkHook.apk`

<img width="1166" alt="image" src="https://github.com/ba0gu0/520apkhook/assets/19379443/65e20013-59a7-4f7e-a17d-ac2996c52e00">


* 最后保存的文件在`a520ApkHook-1.1-jar-with-dependencies.jar`同级目录下的`520ApkBox32.apk`

* 最后自己准备一个安卓的证书，把这个apk重新签名即可。

* 签名参考 [https://github.com/jixiaoyong/ApkSigner](https://github.com/jixiaoyong/ApkSigner)，这个项目直接提供了图形化的签名工具。

**Comment by ba0gu0** [comment]
最新版本已可用。

https://github.com/ba0gu0/520apkhook/releases/download/v1.2/a520ApkHook-1.2.1-jar-with-dependencies.jar
