### ISSUE TITLE
released v1.2 附件版本错误

### ISSUE THREAD

**Issue by Actue** [cleverbao/520apkhook#40]
![image](https://github.com/ba0gu0/520apkhook/assets/33179820/5798822f-41ca-4c84-a31d-8c9e7f5a31ae)
传错版本了好像

**Comment by ba0gu0** [comment]
> ![image](https://private-user-images.githubusercontent.com/33179820/333841689-5798822f-41ca-4c84-a31d-8c9e7f5a31ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Njg5MTgsIm5iZiI6MTcxNjc2ODYxOCwicGF0aCI6Ii8zMzE3OTgyMC8zMzM4NDE2ODktNTc5ODgyMmYtNDFjYS00Yzg0LWEzMWQtOGM5ZTdmNWEzMWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAwMTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MGZlYTM2NWIyNmRmZTVmMzIzOTdiMDNiYTQ0ZDI2NzNmZmMwNmVhOTg1ODlkNDFhZThkZDk2MDY4NTZjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ADuJZ9EnXjihVpupzF-6FV-7KZDzNF4Zi0Lm1GvucA) 传错版本了好像

* 目前apk的签名有问题，还在修复，修复完更新一下。
* 杀软也会报毒，还在修改。

**Comment by ba0gu0** [comment]
已经更新了最新版本，1.2.1，可以过杀软。

https://github.com/ba0gu0/520apkhook/releases/download/v1.2/a520ApkHook-1.2.1-jar-with-dependencies.jar
