### ISSUE TITLE
机器验证包名怎么解决

### ISSUE THREAD

**Issue by moondeft** [cleverbao/520apkhook#41]
我测试的设备有安全机制，会验证包名是否为白名单中的，否则无法安装，假如我要注入的app包名为com.test.apps，在使用你的工具后包名会变为com.test.apps.box导致不匹配白名单无法安装

**Comment by ba0gu0** [comment]
> 我测试的设备有安全机制，会验证包名是否为白名单中的，否则无法安装，假如我要注入的app包名为com.test.apps，在使用你的工具后包名会变为com.test.apps.box导致不匹配白名单无法安装

"-p", "--newPackageName"参数用来指定新生成的包名，不过spacecore和newblackbox用相同的包名可能会导致app启动不起来，具体的需要测试。

包名可以一样，但是签名不对，目前的版本已经把签名的信息改成一样的，但是hash是对不上的，这个没有办法。

**Comment by moondeft** [comment]
好的  谢谢大佬
