### ISSUE TITLE
安装包和系统不兼容

### ISSUE THREAD

**Issue by BestQiang** [cleverbao/520apkhook#42]
小米手机测试打包后的app，安装时显示安装包与系统不兼容

**Comment by ba0gu0** [comment]
> 小米手机测试打包后的app，安装时显示安装包与系统不兼容

能提供一下系统版本，注入的app吗？

**Comment by xiazaidian02** [comment]
有几个问题请教作者 你的那个命令不行 我用得这个
java -jar a520ApkHook-1.2.1-jar-with-dependencies.jar C:\a\a.apk C:\a\b.apk
事先安装了jdk-11.0.23_windows-x64_bin.exe WIN10系统
下载得你这个a520ApkHook-1.2.1-jar-with-dependencies.jar 生成的APK闪退
如果用Kali Linux  Ubuntu 64 位 安装JDK11.0.6运行到V4签名校对就程序退出了
还有你有两个安卓虚拟机 用什么命令切换第二个
你以前的那个main.py  只能注入木马  我是想合并APP
不能用

**Comment by xiazaidian02** [comment]
而且WIN10系统每次生成前必须删除下C:\Users\Administrator\AppData\Local\apktool\framework 下面的1.APK

**Comment by ba0gu0** [comment]
> 小米手机测试打包后的app，安装时显示安装包与系统不兼容

* 闪退问题，可以看下这个回复 [https://github.com/ba0gu0/520apkhook/issues/43#issuecomment-2198847566](https://github.com/ba0gu0/520apkhook/issues/43#issuecomment-2198847566)

* 添加 `-b NewBlackbox` 参数再试一下，还不行，就只能NewBlackbox和SpaceCore更新新版本。
