### ISSUE TITLE
有几个问题 你这个生成的光闪退

### ISSUE THREAD

**Issue by xiazaidian02** [cleverbao/520apkhook#43]
有几个问题请教作者 你的那个命令不行 我用得这个
java -jar a520ApkHook-1.2.1-jar-with-dependencies.jar C:\a\a.apk C:\a\b.apk
事先安装了jdk-11.0.23_windows-x64_bin.exe WIN10系统
下载得你这个a520ApkHook-1.2.1-jar-with-dependencies.jar 生成的APK闪退
如果用Kali Linux Ubuntu 64 位 安装JDK11.0.6运行到V4签名校对就程序退出了
还有你有两个安卓虚拟机 用什么命令切换第二个
你以前的那个main.py 只能注入木马 我是想合并APP
不能用

而且WIN10系统每次生成前必须删除下C:\Users\Administrator\AppData\Local\apktool\framework 下面的1.APK

**Comment by xiazaidian02** [comment]
b.apk 就是他生成的

**Comment by xiazaidian02** [comment]
b.apk就是AhMyth生成的https://github.com/AhMyth/AhMyth-Android-RAT.git 虽然SDK老版本在手机不能用  但是在雷电模拟器能用 我就是测试下你脚本  也不成功 闪退

**Comment by ba0gu0** [comment]
## 简单讲解一下这个项目的实现，有两个版本，第一个版本python实现，主要是注入远控的源码到app中，只支持msf。

* 通过apktool反编译被注入的app，比如微信，然后修改smail代码，把msf远控的相关代码合并到微信的smail代码中，之后重新编译app。
* 
* 生成的新的app，会启动msf远控，同时启动微信app。不过这种方法局限性很大，微信这种没有加固的还好，如果遇到app用了360加固、网易加固之类的，修改app会导致app闪退、甚至反编译都会直接失败。所以上个版本很难用。
* 
* 如果你的app没有进行过加固、或者是解决过壳的问题，比如破解软件，可以使用这个版本的，效果应该比较好，不过只支持msf。
* 
* 也可以支持第三方的远控，不过需要更新代码。

## 第二个版本，使用虚拟机的方式，使用[NewBlackbox](https://github.com/ALEX5402/NewBlackbox)、[SpaceCore](https://github.com/FSpaceCore/SpaceCore) 两个虚拟机，在虚拟机中运行app，不对app做任何修改，就不用考虑app的加固问题了。

* SpaceCore和NewBlackbox会存在兼容问题（依赖第三方项目，没办法），有些时候在虚拟机中运行不了，有些在个别设备中运行不了。需要通过-b参数来指定， -b SpaceCore  或者 -b NewBlackbox 默认是SpaceCore，他的兼容性比较好，但是性能有点差，启动慢，卡。NewBlackbox性能好，启动快，但是兼容差。
* 
* 然后你的软件运行参数有问题，` java -jar a520ApkHook-1.2-jar-with-dependencies.jar app_douyu_7.7.5_10775004_market.apk ./Payload.apk `
* 
* 第一个参数是被注入的app，也就是正常的app，比如斗鱼、微信、京东等，第二个是远控的app，msf、AhMyth等。

**Comment by xiazaidian02** [comment]
不行 用的命令式java -jar a520ApkHook-1.2.1-jar-with-dependencies.jar app_douyu_7.7.6_10776003_market.apk ./b.apk

斗鱼现在是7.76  b.apk 是https://github.com/AhMyth/AhMyth-Android-RAT.git 他生成的  jdk 是jdk-11.0.23_windows-x64_bin.exe
你的那个JAVA程序最新版本是a520ApkHook-1.2.1-jar-with-dependencies.jar
把他们放到一个目录 然后用CMD执行的这个 命令    
还有作者能不能说下你有两个虚拟机  用什么命令切换的虚拟机  
给个例子
生成的这个520ApkHook.zipalign.signer.apk 还是闪退

**Comment by ba0gu0** [comment]
加参数  -b NewBlackbox

jdk-11.0.23 也可以正常用的

**Comment by xiazaidian02** [comment]
你的那个虚拟机不用事先安装吧

我只下载了那个java 然后运行的命令  还有用的AhMyth_Win32.exe  生成的

**Comment by ba0gu0** [comment]
不用，内置了，虚拟机其实就是一个apk文件。

**Comment by xiazaidian02** [comment]
换了AhMyth_Win64.exe 生成的apk 还是闪退   把文件都挪到了520ApkHook  文件夹下还是闪退   
最后问下怎么切换虚拟机的  运行你这命令前需要安装虚拟机吗

**Comment by xiazaidian02** [comment]
你说的加参数 -b NewBlackbox  完整的命令是怎么加 在哪里加

**Comment by ba0gu0** [comment]
`java -jar a520ApkHook-1.2.1-jar-with-dependencies.jar app_douyu_7.7.6_10776003_market.apk ./b.apk -b NewBlackbox `
如果app还是闪退，则说明用不了。只能等NewBlackbox和SpaceCore更新新版本。

**Comment by xiazaidian02** [comment]
我用了这两个命令都不可以  java -jar a520ApkHook-1.2.1-jar-with-dependencies.jar -b SpaceCore app_douyu_7.7.6_10776003_market.apk ./Ahmyth.s.apk.apk

java -jar a520ApkHook-1.2.1-jar-with-dependencies.jar -b NewBlackbox app_douyu_7.7.6_10776003_market.apk ./Ahmyth.s.apk.apk

雷电模拟器闪退

我是直接把你生成的这个文件520ApkHook.zipalign.signer.apk安装的 没管设么其他证书

**Comment by xiazaidian02** [comment]
雷电安卓9.0 64位
