### ISSUE TITLE
执行到最后一步的时候显示对齐失败

### ISSUE THREAD

**Issue by Mrwithnomoney** [cleverbao/520apkhook#45]
![image](https://github.com/ba0gu0/520apkhook/assets/97926637/611a8141-694c-4d83-8f6d-cb33acb8bbfa)
我这里使用的是一个比较老的apk的包，是能正常安装的，请问怎样才可以解决这个问题啊，我换了其他的apk还是不行欸

**Comment by Mrwithnomoney** [comment]
java -jar a520ApkHook-1.2.1-jar-with-dependencies.jar -o V13.1.0-99208-800002996-71738773-32bit.apk game.apk
刚刚执行的上面这个命令
尝试了一遍，还是一样捏，求大佬指导

**Comment by xiazaidian02** [comment]
这个我来告诉你  别用linux虚拟机执行  至于物理机没试过
用WINDOWS10执行
还有你的命令错了 据作者说 就算你把所有东西都放在一个目录
命令也是这样的
java -jar a520ApkHook-1.2.1-jar-with-dependencies.jar -o V13.1.0-99208-800002996-71738773-32bit.apk ./game.apk
少了个./ 你试试这个命令

**Comment by xiazaidian02** [comment]
不过WIN10我也没成功  作者也解决不了 叫等更新

**Comment by Mrwithnomoney** [comment]
那目前是不能使用这个项目去做实验吗？

**Comment by ba0gu0** [comment]
> ![image](https://private-user-images.githubusercontent.com/97926637/344720649-611a8141-694c-4d83-8f6d-cb33acb8bbfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDM5MTksIm5iZiI6MTcxOTkwMzYxOSwicGF0aCI6Ii85NzkyNjYzNy8zNDQ3MjA2NDktNjExYTgxNDEtNjk0Yy00ZDgzLThmNmQtY2IzM2FjYjhiYmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA3MDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZDY5MjcwMjAxOTBkOGFmOTA5YzMzMGM3MjhlMGRiNGJkOTMxMDA1ZDg3MTA3OGQxNWExNTdhZDIyMGJkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YhnEXL2AzLGmyaBvAGZ7FTR2K3MU_FqERTTBUj0PGHc) 我这里使用的是一个比较老的apk的包，是能正常安装的，请问怎样才可以解决这个问题啊，我换了其他的apk还是不行欸

* Linux可以正常运行了。下载最新版本。https://github.com/ba0gu0/520apkhook/releases/download/v1.2/a520ApkHook-1.2.1-jar-with-dependencies.jar

**Comment by Mrwithnomoney** [comment]
是的呀，我用的这个版本，但是到最后一步不成功了

**Comment by ba0gu0** [comment]
> 不过WIN10我也没成功 作者也解决不了 叫等更新

* 这个不成功和jar文件运行是两回事。
* 
* 安卓当中存在一个东西，叫安卓虚拟化，可以理解为安卓中的vm虚拟机，不过这个虚拟机的稳定性不行。
* 当前项目就是依赖于安卓虚拟化，利用一个虚拟化的安卓软件，来运行另外一个app，达到注入的效果。出现打包好的app闪退、运行缓慢，都是因为虚拟化的问题。
* 这个问题想解决，需要等虚拟化软件更新，或者自己重写一个，难度很高。

**Comment by ba0gu0** [comment]
> 是的呀，我用的这个版本，但是到最后一步不成功了

10 分钟前更新的哈，就是看到你这个问题，更新了一下。

**Comment by Mrwithnomoney** [comment]
感谢，我现在去尝试一下

**Comment by Mrwithnomoney** [comment]
![image](https://github.com/ba0gu0/520apkhook/assets/97926637/20a1e0ca-2729-42d2-add2-d80b5997307b)

刚刚尝试了之后，发现无法被雷电模拟器安装，请问这个怎么解决呢？是安卓7.1的版本

**Comment by Mrwithnomoney** [comment]
![image](https://github.com/ba0gu0/520apkhook/assets/97926637/1c8ba80e-25e9-42a1-a9b8-4bb7305928c1)
而且使用了我比较老的apk包去实验也是一样的结果

**Comment by ba0gu0** [comment]
> ![image](https://github.com/ba0gu0/520apkhook/assets/97926637/1c8ba80e-25e9-42a1-a9b8-4bb7305928c1)
> 
> 而且使用了我比较老的apk包去实验也是一样的结果

注意看下程序最后的输出哈，a52apkhook.ziplig.siger.apk 才是最后的程序。
中间生成的那些文件没有删。

**Comment by xiazaidian02** [comment]
520ApkHook.zipalign.signer.apk
只要安装这个是吧 那生成的证书不用管  我还是不知道为什么后面那个apk 要加./
我已经加了还是不行 还买了个安卓6.0手机 还是不行
你检查下是不是你写错JAVA了
我在应用信息里看了下  不论是手机还是雷电模拟器
生成的APP都没获取任何权限 在手机上如果手动赋予他权限 
生成的程序最新版支付宝都能运行 雷电模拟器没法赋予权限运行
你检查下是不是生成的APP没赋予权限的问题

**Comment by xiazaidian02** [comment]
但是远控是附加的没法赋予权限所以也不运行在手机上只能支付宝运行就是手动赋予权限

**Comment by Mrwithnomoney** [comment]
![image](https://github.com/ba0gu0/520apkhook/assets/97926637/7cefcea3-be10-49b3-bae5-b05350658cb7)

呃，我发现在虚拟机上运行apk时会卡退，且无法回弹shell，普通的木马文件能行

**Comment by sagatneed** [comment]
> ![image](https://private-user-images.githubusercontent.com/97926637/346404908-7cefcea3-be10-49b3-bae5-b05350658cb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTI0NDEsIm5iZiI6MTcyNTI5MjE0MSwicGF0aCI6Ii85NzkyNjYzNy8zNDY0MDQ5MDgtN2NlZmNlYTMtYmUxMC00OWIzLWJhZTUtYjA1MzUwNjU4Y2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDE1NDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YzJkNzI3NDdjNGMxMGQ5YTQ5MWM4ZjNhNjA1NmZkNGYzZTNlY2IwNTNjNDVhNmM2NzdhNmJkMjY3NGE3YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GvkMFgQlN2JiQ25GWx_kVvp0bPoB5nXkM1AaKB5m_Tk)
> 
> 呃，我发现在虚拟机上运行apk时会卡退，且无法回弹shell，普通的木马文件能行

兄弟你在模拟器里面运行的话至少还有显示，我现在出现的问题跟你一样，我合成后的apk包可以在模拟器里面安装程序，但是打开安装后的程序就卡死，msf也监听不到任何的设备上线，你现在问题解决了吗？

**Comment by Mrwithnomoney** [comment]
后面解决了，能直接上线，非常方便
