### ISSUE TITLE
无法找到默认启动组件，输入路径提示文件不存在

### ISSUE THREAD

**Issue by xbai8** [cleverbao/520apkhook#9]
腾讯系列app无法找到App默认启动组件.method public onCreate()V，统一输入组件地址为WorkDir/dexfile/app/classes/com/tencent/tinker/loader/app/TinkerApplication.smali
    网易系列闪退暂未解决

按照上面这个路径输入，提示文件不存在

**Comment by leiwuhen92** [comment]
我试了网易新闻、腾讯新闻、最新版微信都不行，但使用微信7.0.22版本可以绕过这步
